spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=dev_distributed_task
    username: mike
    password: zhufuyuan

server:
  port: 9000